sudo: required
services:
  - docker
script:
  - docker build -t hdfelix/react-example .
  - docker images hdfelix/react-example

before_deploy:
  echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push hdfelix/react-example
  on:
    branch: master